INSERT INTO public.mt_btype(
id, created_on, updated_on, is_active, name, seq, type)
VALUES (nextval('mt_btype_id_seq'), now(), now(), true, 'Aerospace & Defence Industry', 0, 'AEROSPACE_DEFENCE'),
      (nextval('mt_btype_id_seq'), now(), now(), true, 'Agriculture industry', 1, 'AGRICULTURE'),
  (nextval('mt_btype_id_seq'), now(), now(), true, 'Bank', 2, 'BANK'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Construction Industry', 3, 'CONSTRUCTION'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Education Industry', 4, 'EDUCATION'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Entertainment Industry', 5, 'ENTERTAINMENT'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Electronics Industry', 6, 'ELECTRONIC'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Energy Industry', 7, 'ENERGY'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Food Industry', 8, 'FOOD'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Health care Industry', 9, 'HEALTH_CARE'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Hospitality Industry', 10, 'HOSPITALITY'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Manufacturing Industry', 11, 'MANUFACTURING'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Metals', 12, 'METALS'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Mining Industry', 13, 'MINING'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'News Media Industry', 14, 'NEWS_MEDIA'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'NGO', 15, 'NGO'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Oil & Naturalgas', 16, 'OIL_NATURALGAS'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Pharmaceutical Industry', 17, 'PHARMACEUTICAL'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Software', 18, 'SOFTWARE'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Sports', 19, 'SPORTS'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Transport Industry', 20, 'TRANSPORT'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Telecommunication industry', 21, 'TELECOMMUNICATION'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Textile Industry', 22, 'TEXTILE'),
(nextval('mt_btype_id_seq'), now(), now(), true, 'Others', 23, 'OTHERS');