INSERT INTO public.mt_country(
	id, created_on, updated_on, is_active, iso_code, name, seq)
	VALUES (nextval('mt_country_id_seq'), now(), now(), true, 'AFG', 'Afghanistan', 0),
(nextval('mt_country_id_seq'), now(), now(), true, 'ALA', 'Aland Islands', 1),
(nextval('mt_country_id_seq'), now(), now(), true, 'ALB', 'Albania', 2),
(nextval('mt_country_id_seq'), now(), now(), true, 'DZA', 'Algeria', 3),
(nextval('mt_country_id_seq'), now(), now(), true, 'ASM', 'American Samoa', 4),
(nextval('mt_country_id_seq'), now(), now(), true, 'AND', 'Andorra', 5),
(nextval('mt_country_id_seq'), now(), now(), true, 'AGO', 'Angola', 6),
(nextval('mt_country_id_seq'), now(), now(), true, 'AIA', 'Anguilla', 7),
(nextval('mt_country_id_seq'), now(), now(), true, 'ATA', 'Antarctica', 8),
(nextval('mt_country_id_seq'), now(), now(), true, 'ATG', 'Antigua and Barbuda', 9),
(nextval('mt_country_id_seq'), now(), now(), true, 'ARG', 'Argentina', 10),
(nextval('mt_country_id_seq'), now(), now(), true, 'ARM', 'Armenia', 11),
(nextval('mt_country_id_seq'), now(), now(), true, 'ABW', 'Aruba', 12),
(nextval('mt_country_id_seq'), now(), now(), true, 'AUS', 'Australia', 13),
(nextval('mt_country_id_seq'), now(), now(), true, 'AUT', 'Austria', 14),
(nextval('mt_country_id_seq'), now(), now(), true, 'AZE', 'Azerbaijan', 15),
(nextval('mt_country_id_seq'), now(), now(), true, 'BHS', 'Bahamas', 16),
(nextval('mt_country_id_seq'), now(), now(), true, 'BHR', 'Bahrain', 17),
(nextval('mt_country_id_seq'), now(), now(), true, 'BGD', 'Bangladesh', 18),
(nextval('mt_country_id_seq'), now(), now(), true, 'BRB', 'Barbados', 19),
(nextval('mt_country_id_seq'), now(), now(), true, 'BLR', 'Belarus', 20),
(nextval('mt_country_id_seq'), now(), now(), true, 'BEL', 'Belgium', 21),
(nextval('mt_country_id_seq'), now(), now(), true, 'BLZ', 'Belize', 22),
(nextval('mt_country_id_seq'), now(), now(), true, 'BEN', 'Benin', 23),
(nextval('mt_country_id_seq'), now(), now(), true, 'BMU', 'Bermuda', 24),
(nextval('mt_country_id_seq'), now(), now(), true, 'BTN', 'Bhutan', 25),
(nextval('mt_country_id_seq'), now(), now(), true, 'BOL', 'Bolivia', 26),
(nextval('mt_country_id_seq'), now(), now(), true, 'BIH', 'Bosnia and Herzegovina', 27),
(nextval('mt_country_id_seq'), now(), now(), true, 'BWA', 'Botswana', 28),
(nextval('mt_country_id_seq'), now(), now(), true, 'BVT', 'Bouvet Island', 29),
(nextval('mt_country_id_seq'), now(), now(), true, 'BRA', 'Brazil', 30),
(nextval('mt_country_id_seq'), now(), now(), true, 'VGB', 'British Virgin Islands', 31),
(nextval('mt_country_id_seq'), now(), now(), true, 'IOT', 'British Indian Ocean TerritoryIOT', 32),
(nextval('mt_country_id_seq'), now(), now(), true, 'BRN', 'Brunei Darussalam', 33),
(nextval('mt_country_id_seq'), now(), now(), true, 'BGR', 'Bulgaria', 34),
(nextval('mt_country_id_seq'), now(), now(), true, 'BFA', 'Burkina Faso', 35),
(nextval('mt_country_id_seq'), now(), now(), true, 'BDI', 'Burundi', 36),
(nextval('mt_country_id_seq'), now(), now(), true, 'KHM', 'Cambodia', 37),
(nextval('mt_country_id_seq'), now(), now(), true, 'CMR', 'Cameroon', 38),
(nextval('mt_country_id_seq'), now(), now(), true, 'CAN', 'Canada', 39),
(nextval('mt_country_id_seq'), now(), now(), true, 'CPV', 'Cape Verde', 40),
(nextval('mt_country_id_seq'), now(), now(), true, 'CYM', 'Cayman Islands', 41),
(nextval('mt_country_id_seq'), now(), now(), true, 'CAF', 'Central African Republic', 42),
(nextval('mt_country_id_seq'), now(), now(), true, 'TCD', 'Chad', 43),
(nextval('mt_country_id_seq'), now(), now(), true, 'CHL', 'Chile', 44),
(nextval('mt_country_id_seq'), now(), now(), true, 'CHN', 'China', 45),
(nextval('mt_country_id_seq'), now(), now(), true, 'HKG', 'Hong Kong, SAR China', 46),
(nextval('mt_country_id_seq'), now(), now(), true, 'MAC', 'Macao, SAR China', 47),
(nextval('mt_country_id_seq'), now(), now(), true, 'CXR', 'Christmas Island', 48),
(nextval('mt_country_id_seq'), now(), now(), true, 'CCK', 'Cocos (Keeling) Islands', 49),
(nextval('mt_country_id_seq'), now(), now(), true, 'COL', 'Colombia', 50),
(nextval('mt_country_id_seq'), now(), now(), true, 'COM', 'Comoros', 51),
(nextval('mt_country_id_seq'), now(), now(), true, 'COG', 'Congo (Brazzaville)', 52),
(nextval('mt_country_id_seq'), now(), now(), true, 'COD', 'Congo, (Kinshasa)', 53),
(nextval('mt_country_id_seq'), now(), now(), true, 'COK', 'Cook Islands', 54),
(nextval('mt_country_id_seq'), now(), now(), true, 'CRI', 'Costa Rica', 55),
(nextval('mt_country_id_seq'), now(), now(), true, 'CIV ', 'Côte d''Ivoire', 56),
(nextval('mt_country_id_seq'), now(), now(), true, 'HRV', 'Croatia', 57),
(nextval('mt_country_id_seq'), now(), now(), true, 'CUB', 'Cuba', 58),
(nextval('mt_country_id_seq'), now(), now(), true, 'CYP', 'Cyprus', 59),
(nextval('mt_country_id_seq'), now(), now(), true, 'CZE', 'Czech Republic', 60),
(nextval('mt_country_id_seq'), now(), now(), true, 'DNK', 'Denmark', 61),
(nextval('mt_country_id_seq'), now(), now(), true, 'DJI', 'Djibouti', 62),
(nextval('mt_country_id_seq'), now(), now(), true, 'DMA', 'Dominica', 63),
(nextval('mt_country_id_seq'), now(), now(), true, 'DOM', 'Dominican Republic', 64),
(nextval('mt_country_id_seq'), now(), now(), true, 'ECU', 'Ecuador', 65),
(nextval('mt_country_id_seq'), now(), now(), true, 'EGY', 'Egypt', 66),
(nextval('mt_country_id_seq'), now(), now(), true, 'SLV', 'El Salvador', 67),
(nextval('mt_country_id_seq'), now(), now(), true, 'GNQ', 'Equatorial Guinea', 68),
(nextval('mt_country_id_seq'), now(), now(), true, 'ERI', 'Eritrea', 69),
(nextval('mt_country_id_seq'), now(), now(), true, 'EST', 'Estonia', 70),
(nextval('mt_country_id_seq'), now(), now(), true, 'ETH', 'Ethiopia', 71),
(nextval('mt_country_id_seq'), now(), now(), true, 'FLK', 'Falkland Islands (Malvinas)', 72),
(nextval('mt_country_id_seq'), now(), now(), true, 'FRO', 'Faroe Islands', 73),
(nextval('mt_country_id_seq'), now(), now(), true, 'FJI', 'Fiji', 74),
(nextval('mt_country_id_seq'), now(), now(), true, 'FIN', 'Finland', 75),
(nextval('mt_country_id_seq'), now(), now(), true, 'FRA', 'France', 76),
(nextval('mt_country_id_seq'), now(), now(), true, 'GUF', 'French Guiana', 77),
(nextval('mt_country_id_seq'), now(), now(), true, 'PYF', 'French Polynesia', 78),
(nextval('mt_country_id_seq'), now(), now(), true, 'ATF', 'French Southern TerritoriesFLK', 79),
(nextval('mt_country_id_seq'), now(), now(), true, 'GAB', 'Gabon', 80),
(nextval('mt_country_id_seq'), now(), now(), true, 'GMB', 'Gambia', 81),
(nextval('mt_country_id_seq'), now(), now(), true, 'GEO', 'Georgia', 82),
(nextval('mt_country_id_seq'), now(), now(), true, 'DEU', 'Germany', 83),
(nextval('mt_country_id_seq'), now(), now(), true, 'GHA', 'Ghana', 84),
(nextval('mt_country_id_seq'), now(), now(), true, 'GIB', 'Gibraltar', 85),
(nextval('mt_country_id_seq'), now(), now(), true, 'GRC', 'Greece', 86),
(nextval('mt_country_id_seq'), now(), now(), true, 'GRL', 'Greenland', 87),
(nextval('mt_country_id_seq'), now(), now(), true, 'GRD', 'Grenada', 88),
(nextval('mt_country_id_seq'), now(), now(), true, 'GLP', 'Guadeloupe', 89),
(nextval('mt_country_id_seq'), now(), now(), true, 'GUM', 'Guam', 90),
(nextval('mt_country_id_seq'), now(), now(), true, 'GTM', 'Guatemala', 91),
(nextval('mt_country_id_seq'), now(), now(), true, 'GGY', 'Guernsey', 92),
(nextval('mt_country_id_seq'), now(), now(), true, 'GIN', 'Guinea', 93),
(nextval('mt_country_id_seq'), now(), now(), true, 'GNB', 'Guinea-Bissau', 94),
(nextval('mt_country_id_seq'), now(), now(), true, 'GUY', 'Guyana', 95),
(nextval('mt_country_id_seq'), now(), now(), true, 'HTI', 'Haiti', 96),
(nextval('mt_country_id_seq'), now(), now(), true, 'HMD', 'Heard and Mcdonald Islands', 97),
(nextval('mt_country_id_seq'), now(), now(), true, 'VAT', 'Holy See (Vatican City State)', 98),
(nextval('mt_country_id_seq'), now(), now(), true, 'HND', 'Honduras', 99),
(nextval('mt_country_id_seq'), now(), now(), true, 'HUN', 'Hungary', 100),
(nextval('mt_country_id_seq'), now(), now(), true, 'ISL', 'Iceland', 101),
(nextval('mt_country_id_seq'), now(), now(), true, 'IND', 'India', 102),
(nextval('mt_country_id_seq'), now(), now(), true, 'IDN', 'Indonesia', 103),
(nextval('mt_country_id_seq'), now(), now(), true, 'IRN', 'Iran, Islamic Republic of', 104),
(nextval('mt_country_id_seq'), now(), now(), true, 'IRQ', 'Iraq', 105),
(nextval('mt_country_id_seq'), now(), now(), true, 'IRL', 'Ireland', 106),
(nextval('mt_country_id_seq'), now(), now(), true, 'IMN', 'Isle of Man', 107),
(nextval('mt_country_id_seq'), now(), now(), true, 'ISR', 'Israel', 108),
(nextval('mt_country_id_seq'), now(), now(), true, 'ITA', 'Italy', 109),
(nextval('mt_country_id_seq'), now(), now(), true, 'JAM', 'Jamaica', 110),
(nextval('mt_country_id_seq'), now(), now(), true, 'JPN', 'Japan', 111),
(nextval('mt_country_id_seq'), now(), now(), true, 'JEY', 'Jersey', 112),
(nextval('mt_country_id_seq'), now(), now(), true, 'JOR', 'Jordan', 113),
(nextval('mt_country_id_seq'), now(), now(), true, 'KAZ', 'Kazakhstan', 114),
(nextval('mt_country_id_seq'), now(), now(), true, 'KEN', 'Kenya', 115),
(nextval('mt_country_id_seq'), now(), now(), true, 'KIR', 'Kiribati', 116),
(nextval('mt_country_id_seq'), now(), now(), true, 'PRK', 'Korea (North)', 117),
(nextval('mt_country_id_seq'), now(), now(), true, 'KOR', 'Korea (South)', 118),
(nextval('mt_country_id_seq'), now(), now(), true, 'KWT', 'Kuwait', 119),
(nextval('mt_country_id_seq'), now(), now(), true, 'KGZ', 'Kyrgyzstan', 120),
(nextval('mt_country_id_seq'), now(), now(), true, 'LAO', 'Lao PDR', 121),
(nextval('mt_country_id_seq'), now(), now(), true, 'LVA', 'Latvia', 122),
(nextval('mt_country_id_seq'), now(), now(), true, 'LBN', 'Lebanon', 123),
(nextval('mt_country_id_seq'), now(), now(), true, 'LSO', 'Lesotho', 124),
(nextval('mt_country_id_seq'), now(), now(), true, 'LBR', 'Liberia', 125),
(nextval('mt_country_id_seq'), now(), now(), true, 'LBY', 'Libya', 126),
(nextval('mt_country_id_seq'), now(), now(), true, 'LIE', 'Liechtenstein', 127),
(nextval('mt_country_id_seq'), now(), now(), true, 'LTU', 'Lithuania', 128),
(nextval('mt_country_id_seq'), now(), now(), true, 'LUX', 'Luxembourg', 129),
(nextval('mt_country_id_seq'), now(), now(), true, 'MKD', 'Macedonia, Republic of', 130),
(nextval('mt_country_id_seq'), now(), now(), true, 'MDG', 'Madagascar', 131),
(nextval('mt_country_id_seq'), now(), now(), true, 'MWI', 'Malawi', 132),
(nextval('mt_country_id_seq'), now(), now(), true, 'MYS', 'Malaysia', 133),
(nextval('mt_country_id_seq'), now(), now(), true, 'MDV', 'Maldives', 134),
(nextval('mt_country_id_seq'), now(), now(), true, 'MLI', 'Mali', 135),
(nextval('mt_country_id_seq'), now(), now(), true, 'MLT', 'Malta', 136),
(nextval('mt_country_id_seq'), now(), now(), true, 'MHL', 'Marshall Islands', 137),
(nextval('mt_country_id_seq'), now(), now(), true, 'MTQ', 'Martinique', 138),
(nextval('mt_country_id_seq'), now(), now(), true, 'MRT', 'Mauritania', 139),
(nextval('mt_country_id_seq'), now(), now(), true, 'MUS', 'Mauritius', 140),
(nextval('mt_country_id_seq'), now(), now(), true, 'MYT', 'Mayotte', 141),
(nextval('mt_country_id_seq'), now(), now(), true, 'MEX', 'Mexico', 142),
(nextval('mt_country_id_seq'), now(), now(), true, 'FSM', 'Micronesia, Federated States of', 143),
(nextval('mt_country_id_seq'), now(), now(), true, 'MDA', 'Moldova', 144),
(nextval('mt_country_id_seq'), now(), now(), true, 'MCO', 'Monaco', 145),
(nextval('mt_country_id_seq'), now(), now(), true, 'MNG', 'Mongolia', 146),
(nextval('mt_country_id_seq'), now(), now(), true, 'MNE', 'Montenegro', 147),
(nextval('mt_country_id_seq'), now(), now(), true, 'MSR', 'Montserrat', 148),
(nextval('mt_country_id_seq'), now(), now(), true, 'MAR', 'Morocco', 149),
(nextval('mt_country_id_seq'), now(), now(), true, 'MOZ', 'Mozambique', 150),
(nextval('mt_country_id_seq'), now(), now(), true, 'MMR', 'Myanmar', 151),
(nextval('mt_country_id_seq'), now(), now(), true, 'NAM', 'Namibia', 152),
(nextval('mt_country_id_seq'), now(), now(), true, 'NRU', 'Nauru', 153),
(nextval('mt_country_id_seq'), now(), now(), true, 'NPL', 'Nepal', 154),
(nextval('mt_country_id_seq'), now(), now(), true, 'NLD', 'Netherlands', 155),
(nextval('mt_country_id_seq'), now(), now(), true, 'ANT', 'Netherlands Antilles', 156),
(nextval('mt_country_id_seq'), now(), now(), true, 'NCL', 'New Caledonia', 157),
(nextval('mt_country_id_seq'), now(), now(), true, 'NZL', 'New Zealand', 158),
(nextval('mt_country_id_seq'), now(), now(), true, 'NIC', 'Nicaragua', 159),
(nextval('mt_country_id_seq'), now(), now(), true, 'NER', 'Niger', 160),
(nextval('mt_country_id_seq'), now(), now(), true, 'NGA', 'Nigeria', 161),
(nextval('mt_country_id_seq'), now(), now(), true, 'NIU', 'Niue', 162),
(nextval('mt_country_id_seq'), now(), now(), true, 'NFK', 'Norfolk Island', 163),
(nextval('mt_country_id_seq'), now(), now(), true, 'MNP', 'Northern Mariana Islands', 164),
(nextval('mt_country_id_seq'), now(), now(), true, 'NOR', 'Norway', 165),
(nextval('mt_country_id_seq'), now(), now(), true, 'OMN', 'Oman', 166),
(nextval('mt_country_id_seq'), now(), now(), true, 'PAK', 'Pakistan', 167),
(nextval('mt_country_id_seq'), now(), now(), true, 'PLW', 'Palau', 168),
(nextval('mt_country_id_seq'), now(), now(), true, 'PSE', 'Palestinian Territory', 169),
(nextval('mt_country_id_seq'), now(), now(), true, 'PAN', 'Panama', 170),
(nextval('mt_country_id_seq'), now(), now(), true, 'PNG', 'Papua New Guinea', 171),
(nextval('mt_country_id_seq'), now(), now(), true, 'PRY', 'Paraguay', 172),
(nextval('mt_country_id_seq'), now(), now(), true, 'PER', 'Peru', 173),
(nextval('mt_country_id_seq'), now(), now(), true, 'PHL', 'Philippines', 174),
(nextval('mt_country_id_seq'), now(), now(), true, 'PCN', 'Pitcairn', 175),
(nextval('mt_country_id_seq'), now(), now(), true, 'POL', 'Poland', 176),
(nextval('mt_country_id_seq'), now(), now(), true, 'PRT', 'Portugal', 177),
(nextval('mt_country_id_seq'), now(), now(), true, 'PRI', 'Puerto Rico', 178),
(nextval('mt_country_id_seq'), now(), now(), true, 'QAT', 'Qatar', 179),
(nextval('mt_country_id_seq'), now(), now(), true, 'REU', 'Réunion', 180),
(nextval('mt_country_id_seq'), now(), now(), true, 'ROU', 'Romania', 181),
(nextval('mt_country_id_seq'), now(), now(), true, 'RUS', 'Russian Federation', 182),
(nextval('mt_country_id_seq'), now(), now(), true, 'RWA', 'Rwanda', 183),
(nextval('mt_country_id_seq'), now(), now(), true, 'BLM', 'Saint-Barthélemy', 184),
(nextval('mt_country_id_seq'), now(), now(), true, 'SHN', 'Saint Helena', 185),
(nextval('mt_country_id_seq'), now(), now(), true, 'KNA', 'Saint Kitts and Nevis', 186),
(nextval('mt_country_id_seq'), now(), now(), true, 'LCA', 'Saint Lucia', 187),
(nextval('mt_country_id_seq'), now(), now(), true, 'MAF', 'Saint-Martin (French part)', 188),
(nextval('mt_country_id_seq'), now(), now(), true, 'SPM', 'Saint Pierre and Miquelon', 189),
(nextval('mt_country_id_seq'), now(), now(), true, 'VCT', 'Saint Vincent and Grenadines', 190),
(nextval('mt_country_id_seq'), now(), now(), true, 'WSM', 'Samoa', 191),
(nextval('mt_country_id_seq'), now(), now(), true, 'SMR', 'San Marino', 192),
(nextval('mt_country_id_seq'), now(), now(), true, 'STP', 'Sao Tome and Principe', 193),
(nextval('mt_country_id_seq'), now(), now(), true, 'SAU', 'Saudi Arabia', 194),
(nextval('mt_country_id_seq'), now(), now(), true, 'SEN', 'Senegal', 195),
(nextval('mt_country_id_seq'), now(), now(), true, 'SRB', 'Serbia', 196),
(nextval('mt_country_id_seq'), now(), now(), true, 'SYC', 'Seychelles', 197),
(nextval('mt_country_id_seq'), now(), now(), true, 'SLE', 'Sierra Leone', 198),
(nextval('mt_country_id_seq'), now(), now(), true, 'SGP', 'Singapore', 199),
(nextval('mt_country_id_seq'), now(), now(), true, 'SVK', 'Slovakia', 200),
(nextval('mt_country_id_seq'), now(), now(), true, 'SVN', 'Slovenia', 201),
(nextval('mt_country_id_seq'), now(), now(), true, 'SLB', 'Solomon Islands', 202),
(nextval('mt_country_id_seq'), now(), now(), true, 'SOM', 'Somalia', 203),
(nextval('mt_country_id_seq'), now(), now(), true, 'ZAF', 'South Africa', 204),
(nextval('mt_country_id_seq'), now(), now(), true, 'SGS', 'South Georgia and the South Sandwich Islands', 205),
(nextval('mt_country_id_seq'), now(), now(), true, 'SSD', 'South Sudan', 206),
(nextval('mt_country_id_seq'), now(), now(), true, 'ESP', 'Spain', 207),
(nextval('mt_country_id_seq'), now(), now(), true, 'LKA', 'Sri Lanka', 208),
(nextval('mt_country_id_seq'), now(), now(), true, 'SDN', 'Sudan', 209),
(nextval('mt_country_id_seq'), now(), now(), true, 'SUR', 'Suriname', 210),
(nextval('mt_country_id_seq'), now(), now(), true, 'SJM', 'Svalbard and Jan Mayen Islands', 211),
(nextval('mt_country_id_seq'), now(), now(), true, 'SWZ', 'Swaziland', 212),
(nextval('mt_country_id_seq'), now(), now(), true, 'SWE', 'Sweden', 213),
(nextval('mt_country_id_seq'), now(), now(), true, 'CHE', 'Switzerland', 214),
(nextval('mt_country_id_seq'), now(), now(), true, 'SYR', 'Syrian Arab Republic (Syria)', 215),
(nextval('mt_country_id_seq'), now(), now(), true, 'TWN', 'Taiwan, Republic of China', 216),
(nextval('mt_country_id_seq'), now(), now(), true, 'TJK', 'Tajikistan', 217),
(nextval('mt_country_id_seq'), now(), now(), true, 'TZA', 'Tanzania, United Republic of', 218),
(nextval('mt_country_id_seq'), now(), now(), true, 'THA', 'Thailand', 219),
(nextval('mt_country_id_seq'), now(), now(), true, 'TLS', 'Timor-Leste', 220),
(nextval('mt_country_id_seq'), now(), now(), true, 'TGO', 'Togo', 221),
(nextval('mt_country_id_seq'), now(), now(), true, 'TKL', 'Tokelau', 222),
(nextval('mt_country_id_seq'), now(), now(), true, 'TON', 'Tonga', 223),
(nextval('mt_country_id_seq'), now(), now(), true, 'TTO', 'Trinidad and Tobago', 224),
(nextval('mt_country_id_seq'), now(), now(), true, 'TUN', 'Tunisia', 225),
(nextval('mt_country_id_seq'), now(), now(), true, 'TUR', 'Turkey', 226),
(nextval('mt_country_id_seq'), now(), now(), true, 'TKM', 'Turkmenistan', 227),
(nextval('mt_country_id_seq'), now(), now(), true, 'TCA', 'Turks and Caicos Islands', 228),
(nextval('mt_country_id_seq'), now(), now(), true, 'TUV', 'Tuvalu', 229),
(nextval('mt_country_id_seq'), now(), now(), true, 'UGA', 'Uganda', 230),
(nextval('mt_country_id_seq'), now(), now(), true, 'UKR', 'Ukraine', 231),
(nextval('mt_country_id_seq'), now(), now(), true, 'ARE', 'United Arab Emirates', 232),
(nextval('mt_country_id_seq'), now(), now(), true, 'GBR', 'United Kingdom', 233),
(nextval('mt_country_id_seq'), now(), now(), true, 'USA', 'United States of America', 234),
(nextval('mt_country_id_seq'), now(), now(), true, 'UMI', 'US Minor Outlying Islands', 235),
(nextval('mt_country_id_seq'), now(), now(), true, 'URY', 'Uruguay', 236),
(nextval('mt_country_id_seq'), now(), now(), true, 'UZB', 'Uzbekistan', 237),
(nextval('mt_country_id_seq'), now(), now(), true, 'VUT', 'Vanuatu', 238),
(nextval('mt_country_id_seq'), now(), now(), true, 'VEN', 'Venezuela (Bolivarian Republic)', 239),
(nextval('mt_country_id_seq'), now(), now(), true, 'VNM', 'Viet Nam', 240),
(nextval('mt_country_id_seq'), now(), now(), true, 'VIR', 'Virgin Islands, US', 241),
(nextval('mt_country_id_seq'), now(), now(), true, 'WLF', 'Wallis and Futuna Islands', 242),
(nextval('mt_country_id_seq'), now(), now(), true, 'ESH', 'Western Sahara', 243),
(nextval('mt_country_id_seq'), now(), now(), true, 'YEM', 'Yemen', 244),
(nextval('mt_country_id_seq'), now(), now(), true, 'ZMB', 'Zambia', 245),
(nextval('mt_country_id_seq'), now(), now(), true, 'ZWE', 'Zimbabwe', 246);