package com.idea.buzzcolony.enums.master;

/**
 * @author Anand Ramesh
 * @version 1.0
 * @since 07/02/21
 */
public enum MtBTypeEnum {
    AEROSPACE_DEFENCE, AGRICULTURE, BANK, CONSTRUCTION, EDUCATION, ENTERTAINMENT, ELECTRONIC, ENERGY, FOOD, HEALTH_CARE,
    HOSPITALITY, MANUFACTURING, METALS, MINING, NEWS_MEDIA, OIL_NATURALGAS, PHARMACEUTICAL, SOFTWARE, SPORT, TRANSPORT, TELECOMMUNICATION, TEXTILE, OTHERS;
}
