package com.idea.buzzcolony.enums.master;

/**
 * @author Anand Ramesh
 * @version 1.0
 * @since 07/02/21
 */
public enum MtSubBtypeEnum {
    AIRLINES, DEFENCE, AGRICULTURE_SEEDS, AQUACULTURE, DAIRY, FERTILIZERS, FOOD_INGREDIENTS, MEAT_PRODUCTS, POULTRY, PRIVATE,
    PUBLIC, DEVELOPMENT_CONSTRUCTION, DEVELOPMENT_REAL_ESTATE, REAL_ESTATE_DEVELOPMENT_OPERATIONS, RESIDENTIAL_COMMERCIAL_COMPLEXES,
    INFRASTRUCTURE, FLAT_SALES, SITE_SALES, CARBON_BLACK, CEMENT, MARBLE, GRANITE, SANITARYWARE, COLLEGE, LABBS_LIFE_SCIENCES,
    ONLINE_SERVICES, SCHOOLS, ACTING, AMUSEMENT_PARKS, ART, CLUB, CREATIVE, DANCE, FILMS, MUSIC, PHOTOGRAPHY, PRODUCTION,
    SHORTFILMS, AIR_CONDITIONERS, COMPUTER_PERIPHERALS, ELECTRIC_EQUIPMENT, BOILERS_TURBINES, SWITCH_GEARS, TRANSFORMERS,
    ELECTRODES_ELECTRIC_EQUIPMENT, ELECTRODES_WELDING_EQUIPMENT, ELECTRONIC_GOODS, WATCHES_ACCESSORIES, ELECTRIC_STATIONS,
    POWER_GENERATION_DISTRIBUTION, RENEWABLES, FUEL_STATIONS, BEVERAGES, CATERERS, CONSUMER_FOOD, DISTILLERIES, GROCERIES_SHOPS,
    VEGETABLE_OILS, SNACKS, BIOTECHNOLOGY, HOSPITAL_HEALTHCARE, MEDICAL_RESEARCH, MEDICAL_STORES, OPTICALS, HOTEL, RESORT, RESTAURANTS,
    ABRASIVES, ALUMINIUM_PRODUCTS, AUTO_ANCILLARIES, AIR_CONDITIONING_AUTO_ANCILLARIES, AUTO_TRUCK_MOTORCYCLE_AUTO_ANCILLARIES,
    AXLE_AUTO_ANCILLARIES, BEARINGS_AUTO_ANCILLARIES, BRAKES_AUTO_ANCILLARIES, BUSBODY_AUTO_ANCILLARIES, CASTINGS_FORGINGS_AUTO_ANCILLARIES,
    CYCLES_BICYCLES, CLUTCHES_AUTO_ANCILLARIES, DIESEL_ENGINES_AUTO_ANCILLARIES, ENGINE_PARTS_AUTO_ANCILLARIES, GEARS_AUTO_ANCILLARIES,
    HEAD_LAMPS_AUTO_ANCILLARIES, PISTONS_AUTO_ANCILLARIES, SEATING_COVERS_AUTO_ANCILLARIES, SHEET_METALS_AUTO_ANCILLARIES,
    SHOCK_ABSORBERS_AUTO_ANCILLARIES, SPARE_ACCESSORIES_AUTO_ANCILLARIES,SPRINGS_AUTO_ANCILLARIES, TYRES_AUTO_ANCILLARIES,
    WHEELS_AUTO_ANCILLARIES, AUTO_TRUCK_AUTO_ANCILLARIES, DEALERS_DISTRIBUTORS_AUTO_ANCILLARIES, LCVS_HVCS_AUTO_ANCILLARIES,
    PASSENGER_AUTO_ANCILLARIES, TRACTORS_AUTO_ANCILLARIES, TRUCKS_LCVS_AUTO_ANCILLARIES, BATTERIES, COMPRESSORS_PUMPS,
    CONTAINERS_PACKAGING, DETERGENTS_SOAPS, FOOTWARE, LEATHER, PLASTIC_PRODUCTS, MOULDED_ARTICLES_PLASTIC_PRODUCTS, PET_BOTTELS_JARS_CONTAINERS_PLASTIC_PRODUCTS,
    SELF_ADHESIVE_TAPES_PLASTIC_PRODUCTS, THERMOPLASTICS_PLASTIC_PRODUCTS, TUBES_PIPES_HOSES_PLASTIC_PRODUCTS, RUBBER_PRODUCTS,
    WOOD_WOOD_PRODUCTS, JEWELLERY, COAL, SPECIALTY_MINING_METALS, CABLE_DH, PRINTING_PUBLISHING, PRINTING_STATIONERY, SOCIAL_MEDIA,
    NGO, GAS, OIL, SOAP, SPECIALITY_CHEMICALS, PAINTS, FOREST_PRODUCTS, PESTICIDES_AGROCHEMICALS, PHARMACEUTICALS_DRUGS,
    BPO_ITES, IT_EDUCATION, IT_NETWORKING, IT_SERVICES_CONSULTING, ARCHERY, BADMINTON, BASKETBALL, BOXING, BUNGEE_JUMPING,
    CIRCKET, CYCLING, DARTS, FENCING, FIGURE_SKATING, FISHING, FOOTBALL, GOLF, GYM, GYMNASTICS, HANDBALL, HANG_GLIDING,
    HOCKEY, HORCE_RACING, ICE_HOCKEY, ICE_SKATING, INDORE_GAMES, JET_SKIING, JUDO, KARATE, KICKBOXING, ROCK_CLIMBING,
    ROLLER_SKATING, RUNNING, RUGBY, SKY_DIVING, SCUBA_DIVING, SUMO_WRESTLING, SKATE_BOARDING, SNOW_BOARDING, SURFING, SWIMMING,
    TABLE_TENNIS, TENNIS, TAEKWONDO, VOLLERBALL, WEIGHT_LIFTING, WIND_SURFING, COURIER, SHIP_BUILDING, SHIPPING, TRANSPORT_INFRASTRUCTURE,
    TRAVEL_SERVICES, TELE_EQUIPMENT, TELE_SERVICE_PROVIDER, TELE_SERVICES, TEXTILE_SPINNING, TEXTILES, TEXTILES_APPAREL, OTHERS
}
